#!/bin/bash
echo "hello world"
mkdir thiswasgeneratedbyremotescript
echo "cattt"
cat << EOF > package.json
{
  "name": "$1",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "start": "parcel ./*.html",
    "predeploy": "rm -rf dist && rm -rf .parcel-cache/ &&  parcel build ./*.html --public-url ./",
    "deploy": "gh-pages -d dist"
  }
}
EOF
npm i
echo "rev"






