#!/bin/bash
mkdir src public
cat << EOF > package.json
{
  "name": "$1",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "start": "parcel ./*.html",
    "predeploy": "rm -rf dist && rm -rf .parcel-cache/ &&  parcel build ./*.html --public-url ./",
    "deploy": "gh-pages -d dist"
  }
}
EOF

cat << EOF > index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- <link rel="icon" type="image/svg+xml" href="./public/favicon.ico" /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Parcel App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
EOF

cat << EOF > src/main.jsx
import React from "react"
import ReactDOM from "react-dom/client"
import App from "./App.jsx"

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
EOF

cat << EOF > src/App.jsx
import { useState } from "react"
import "./App.css"

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <h1>Parcel App!</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
    </>
  )
}

export default App
EOF

cat << EOF > src/App.css
#root {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.card {
  padding: 2em;
}
EOF

npm i --save-dev gh-pages && npm i react react-dom

echo "All set! Now you can do:"
echo "npm run deploy"




